# Use cargo make to run scripts in this file. Most scripts are used to provide safe defaults for
# standard operations (generate docs with mermaid and KaTeX support, run benchmarks with shilds_up
# disabled, ...)

# Enable docs with Mermaid, KaTeX and some small design tweaks.
[tasks.rich-doc-dev]
env = { "RUSTDOCFLAGS" = "--html-in-header ./res/docs-head.html" }
command = "cargo"
args = ["doc", "--no-deps", "--document-private-items"]

[tasks.rich-doc]
env = { "RUSTDOCFLAGS" = "--html-in-header ./res/docs-head.html" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.all]
dependencies = [
    "docs",
    "doc-katex",
]

# Make a release build with shields_up enabled.
[tasks.build-release-safe]
command = "cargo"
args = ["build", "--release", "--features", "shields_up"]

# Make a debug build with shields_up enabled.
[tasks.build-safe]
command = "cargo"
args = ["build", "--features", "shields_up"]

# Make a test build with shields_up enabled.
[tasks.test-safe]
command = "cargo"
args = ["test", "--features", "shields_up"]